---
title: "Sknifedatar: R-Rosario"
description: |
  Ejemplo automagic tabs para predicciones de modelos.
author:
  - first_name: "Rafael"
    last_name: "Zambrano"
    url: https://rafael-zambrano-blog-ds.netlify.app/
  - first_name: "Karina"
    last_name: "Bartolomé"
    url: https://karbartolome-blog.netlify.app/
    affiliation: R-Rosario
    affiliation_url: https://renrosario.rbind.io/
date: 10-06-2021
output:
  distill::distill_article:
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      comment=FALSE)
```

-   Librerias

```{r}
library(sknifedatar)
library(tidymodels)
library(tidyverse)
library(probably)
library(modeldata)
library(skimr)
library(rmarkdown)
library(gtsummary)
```

-   Datos

```{r}
data(credit_data)

credit_data <- credit_data %>% 
  drop_na() %>% 
  mutate(Status = fct_relevel(Status, "bad"))

head(credit_data) %>% paged_table()
```

```{r}
skim(credit_data)
```

```{r}
set.seed(123)
splits <- initial_split(credit_data)
train <- training(splits)
test  <- testing(splits)
```

```{r}
#Modelo
modelo <- logistic_reg() 

#Receta
receta <- recipe(Status ~ ., data = train) %>% 
  
  step_normalize(all_numeric_predictors()) %>% 
  
  step_dummy(all_nominal_predictors())

#workflow
workflow_credito <- workflow() %>% 
  
  add_model(modelo) %>% 
  
  add_recipe(receta)
```

```{r}
predicciones <- workflow_credito %>% 
  
  fit(train) %>% 
  
  augment(test)


head(predicciones) %>% paged_table()
```

```{r}
predicciones %>% 
  
  conf_mat(Status, .pred_class) %>% 
  
  autoplot(type = "heatmap")
```

```{r}
predicciones %>% 
  
  mutate(.pred_class = make_two_class_pred(.pred_bad,
                                           levels(Status), threshold = 0.7)) %>% 
  
  select(Status, .pred_class) %>% 
  
  conf_mat(Status, .pred_class) %>% 
  
  autoplot(type = "heatmap")
```

```{r}
thresholds_cuts <- predicciones$.pred_bad %>% 
  quantile(seq(0,1,0.1)) %>% 
  round(2)

thresholds_cuts

thresholds_cuts %>% plot()
```

```{r}
thresholds_tibble <- tibble(thresholds = thresholds_cuts) %>%
  
  mutate(matrices_plot = map(thresholds, ~ predicciones %>%
                               
                   mutate(.pred_class = make_two_class_pred(.pred_bad,
                                                            levels(Status),
                                                            threshold = .x)) %>% 
                               
                               select(Status, .pred_class) %>% 
                               
                               conf_mat(Status, .pred_class) %>% 
                               
                               autoplot(type = "heatmap")))

thresholds_tibble
```

```{r}
thresholds_tibble$matrices_plot[[1]]
```

-   Tabs

```{r ,echo=FALSE}
xaringanExtra::use_panelset()
```

`r automagic_tabs(input_data = thresholds_tibble, panel_name = "thresholds", .output = "matrices_plot")`
