---
title: "Sknifedatar: R-Rosario"
description: |
  Ejemplo automagic tabs2 para análisis de modelos.
author:
  - first_name: "Rafael"
    last_name: "Zambrano"
    url: https://rafael-zambrano-blog-ds.netlify.app/
  - first_name: "Karina"
    last_name: "Bartolomé"
    url: https://karbartolome-blog.netlify.app/
    affiliation: R-Rosario
    affiliation_url: https://renrosario.rbind.io/
date: 10-06-2021
output:
  distill::distill_article:
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      comment=FALSE)
```

-   Librerias

```{r}
library(sknifedatar)
library(tidymodels)
library(tidyverse)
library(modeldata)
library(rmarkdown)
library(gtsummary)
library(performance)
library(see)
```

-   Datos

```{r}
data(credit_data)

credit_data <- credit_data %>% 
  drop_na() %>%
  select(- c(Marital, Job, Records, Seniority, Expenses, Income, Amount)) %>% 
  mutate(Status = fct_relevel(Status, "bad"))
```

```{r}
dataset <- credit_data %>% nest(datos = -Home)

#dataset
```

```{r}
dataset <- dataset %>% filter(Home != "ignore")
```

```{r}
# dataset$datos[[1]] %>% head()
```

```{r}
#Modelo
modelo <- logistic_reg() 

#Receta
receta <- recipe(Status ~ ., data = dataset$datos[[1]]) %>% 
  
  step_normalize(all_numeric_predictors()) %>% 
  
  step_dummy(all_nominal_predictors())

#workflow
workflow_credito <- workflow() %>% 
  
  add_model(modelo) %>% 
  
  add_recipe(receta)
```

```{r}
output_final <- dataset %>% 
  
  mutate(modelo = map(datos, ~ workflow_credito %>% 
                        fit(.x) %>% 
                        extract_fit_engine()))
```

```{r}
#output_final
```

```{r}
#output_final$modelo[[1]]
```

```{r}
output_final <- output_final %>% 
  
  mutate(graficos = map(modelo, ~ check_model(.x, check = "vif")))
```

```{r}
#output_final
```

```{r}
#output_final$graficos[[1]]
```


```{r}
output_final <- output_final %>% 
  
  mutate(tabla_modelo = map(modelo, ~ tbl_regression(.x, exponentiate = TRUE) %>% 
                             bold_p(t = 0.15) %>%
                             bold_labels() %>% 
                             as_gt() %>%
                             gt::tab_source_note(gt::md("Fuente: R-Rosario*"))))
```

```{r}
#output_final
```

```{r}
#output_final$tabla_modelo[[1]]
```

-   Tabs

```{r ,echo=FALSE}
xaringanExtra::use_panelset()
```

`r automagic_tabs2(input_data = output_final, panel_name = Home, graficos, tabla_modelo)`
